### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jonmjauu** [Autist69420/Discord.js-Obfuscator-Bot#1]
As the obfuscator doesnt have any help themself ill try to get help here i am gettting this error:
[here](https://prnt.sc/u27nby)

**Comment by Autist69420** [comment]
you need to download luaforwindows [here](https://github.com/rjpcomputing/luaforwindows/releases)

**Comment by jonmjauu** [comment]
Alright thank you. Just saying it would be good to note that in the readme.md 👍

**Comment by Autist69420** [comment]
yea ill add that
